import * as childProcess from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { AgentPreset } from '../shared/types';
import { getAppDataDir } from '../shared/instance';

export const PROXYAPI_KEY_ENV = 'PROXYAPI_KEY';
const PROXYAPI_ANTHROPIC_URL = 'https://api.proxyapi.ru/anthropic';
const PROXYAPI_OPENAI_URL = 'https://api.proxyapi.ru/openai/v1';

export interface AgentReadiness {
  proxyApiConfigured: boolean;
  claudeCodeAvailable: boolean;
  codexAvailable: boolean;
}

export interface AgentLaunch {
  env: Record<string, string>;
}

export function getAgentStartupCommand(
  preset: AgentPreset,
  resume: boolean,
  platform: NodeJS.Platform = process.platform,
): string {
  const base = preset === 'claude-code' ? 'claude' : 'codex';
  const command = platform === 'win32' ? `${base}.cmd` : base;
  if (!resume) return command;
  return preset === 'claude-code' ? `${command} --resume` : `${command} resume`;
}

function commandExists(command: string): boolean {
  try {
    childProcess.execFileSync(process.platform === 'win32' ? 'where' : 'which', [
      process.platform === 'win32' ? `${command}.*` : command,
    ], {
      windowsHide: true,
      timeout: 3000,
      stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

function getProxyApiKey(env: NodeJS.ProcessEnv): string | undefined {
  const key = env[PROXYAPI_KEY_ENV]?.trim();
  return key && key.length >= 8 ? key : undefined;
}

/** Deliberately returns only booleans: the renderer never receives a credential. */
export function getAgentReadiness(env: NodeJS.ProcessEnv = process.env): AgentReadiness {
  return {
    proxyApiConfigured: Boolean(getProxyApiKey(env)),
    claudeCodeAvailable: commandExists('claude'),
    codexAvailable: commandExists('codex'),
  };
}

function getCodexHome(): string {
  return path.join(getAppDataDir(), 'agent-runtime', 'codex');
}

export function getCodexProxyConfig(): string {
  return [
    '# Generated by WinAgent Terminal. This file contains no credentials.',
    'model_provider = "proxyapi"',
    '',
    '[model_providers.proxyapi]',
    'name = "ProxyAPI"',
    `base_url = "${PROXYAPI_OPENAI_URL}"`,
    'env_key = "PROXYAPI_KEY"',
    'wire_api = "responses"',
    'supports_websockets = false',
    '',
  ].join('\n');
}

/** Pure provider mapping, suitable for regression tests and diagnostics. */
export function buildProxyApiEnvironment(preset: AgentPreset, key: string): Record<string, string> {
  if (preset === 'claude-code') {
    return {
      [PROXYAPI_KEY_ENV]: key,
      ANTHROPIC_BASE_URL: PROXYAPI_ANTHROPIC_URL,
      ANTHROPIC_AUTH_TOKEN: key,
    };
  }
  return { [PROXYAPI_KEY_ENV]: key };
}

/**
 * Keep the Codex provider configuration isolated from the user's ~/.codex.
 * It contains no credentials and is atomically refreshed before each launch.
 */
function ensureCodexConfig(): string {
  const home = getCodexHome();
  fs.mkdirSync(home, { recursive: true });
  const configPath = path.join(home, 'config.toml');
  const content = getCodexProxyConfig();
  const temporary = `${configPath}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, content, { encoding: 'utf-8', mode: 0o600 });
  fs.renameSync(temporary, configPath);
  return home;
}

/**
 * Builds a launch plan in the main process. The secret only enters the spawned
 * PTY environment and is never serialised, logged, persisted or returned over IPC.
 */
export function buildAgentLaunch(preset: AgentPreset, env: NodeJS.ProcessEnv = process.env): AgentLaunch {
  const key = getProxyApiKey(env);
  if (preset === 'claude-code') {
    if (!commandExists('claude')) throw new Error('Claude Code CLI was not found on PATH.');
    if (!key) return { env: {} };
    return {
      env: buildProxyApiEnvironment(preset, key),
    };
  }

  if (!commandExists('codex')) throw new Error('Codex CLI was not found on PATH.');
  if (!key) return { env: {} };
  return {
    env: { ...buildProxyApiEnvironment(preset, key), CODEX_HOME: ensureCodexConfig() },
  };
}

/** Redact before diagnostics ever leave the main process. */
export function redactSecrets(value: string, env: NodeJS.ProcessEnv = process.env): string {
  const key = getProxyApiKey(env);
  let output = value;
  if (key) output = output.split(key).join('[REDACTED]');
  return output.replace(/(authorization\s*[:=]\s*)(bearer\s+)?[^\s,;]+/gi, '$1[REDACTED]');
}
